# Generated by Django 3.1 on 2020-09-16 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtomResponderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=32768)),
                ('type', models.TextField(max_length=128)),
                ('projectId', models.TextField(max_length=128)),
                ('atomId', models.UUIDField()),
                ('user', models.TextField(max_length=32768)),
                ('jobId', models.TextField(max_length=128, validators=[django.core.validators.RegexValidator('^\\w{2}-\\d+')])),
                ('itemId', models.TextField(max_length=128, validators=[django.core.validators.RegexValidator('^\\w{2}-\\d+')])),
            ],
        ),
    ]
