# Generated by Django 3.1 on 2020-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomrespondermessage',
            name='atime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atomrespondermessage',
            name='ctime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atomrespondermessage',
            name='mtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='atomrespondermessage',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
