# Generated by Django 3.1 on 2020-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0002_auto_20200917_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
