# Generated by Django 3.1 on 2020-09-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0003_auto_20200917_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='atime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='ctime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='mtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
