# Generated by Django 3.1.7 on 2021-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0005_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='projectId',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
