# Generated by Django 3.1.9 on 2021-05-12 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0006_auto_20210402_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='commissionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='itemId',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='atomrespondermessage',
            name='jobId',
            field=models.TextField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator('^\\w{2}-\\d+')]),
        ),
    ]
