# Generated by Django 3.1.13 on 2021-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbitmq', '0007_auto_20210512_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragetierSuccessMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiveHunterID', models.TextField(max_length=32768)),
                ('archiveHunterIDValidated', models.BooleanField()),
                ('originalFilePath', models.TextField(max_length=32768)),
                ('uploadedBucket', models.TextField(max_length=128)),
                ('uploadedPath', models.TextField(max_length=32768)),
                ('uploadedVersion', models.IntegerField(blank=True, null=True)),
                ('vidispineItemId', models.TextField(blank=True, max_length=128, null=True)),
                ('vidispineVersionId', models.IntegerField(blank=True, null=True)),
                ('proxyBucket', models.TextField(max_length=128)),
                ('proxyPath', models.TextField(max_length=32768)),
                ('proxyVersion', models.IntegerField(blank=True, null=True)),
                ('metadataXML', models.TextField(max_length=32768)),
                ('metadataVersion', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
