stages:
  - buildntest
  - upload

django:
  image: python:3.8-alpine
  stage: buildntest
  services:
    - postgres:9.6
  variables:
    POSTGRES_DB: pluto-deliverables
    POSTGRES_USER: pluto-deliverables
    POSTGRES_PASSWORD: pluto-deliverables
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - apk add postgresql-dev alpine-sdk
    - git submodule init
    - git submodule update
    - pip install -r requirements.txt
    - pip install -r gnmvidispine/requirements.txt
    - cd gnmvidispine && CIRCLE_BUILD_NUM=$CI_PIPELINE_IID python ./setup.py install && cd ..
    - python ./manage.py test gnm_deliverables.tests

frontend:
  image: node:12.18-alpine3.12
  stage: buildntest
  script:
    - cd frontend
    - yarn install
    - yarn lint
    - yarn test
    - yarn build:prod
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - frontend/node_modules/
  artifacts:
    paths:
      - gnm_deliverables/static/app.js
    reports:
      junit: frontend/junit.xml


upload:
  image: "docker:19.03.11"
  stage: upload
  services:
    - docker:dind

  script:
    - apk add git
    - git submodule init
    - git submodule update
    - docker build . -t guardianmultimedia/pluto-deliverables:$CI_PIPELINE_IID
    - docker login -u "${DOCKER_USER}" -p "${DOCKER_PAT}"
    - docker push guardianmultimedia/pluto-deliverables:$CI_PIPELINE_IID
