from portal.plugins.gnm_vidispine_utils import vs_calls, constants as const
from portal.plugins.gnm_vidispine_utils.md_utils import tag
from portal.plugins.gnm_metadataform.forms import metadataform_factory
from portal.plugins.gnm_misc_utils.helpers import parse_xml
from django.forms import Form, CharField, TextInput, URLField
from django.utils.safestring import mark_safe
from django.db import IntegrityError

import urllib.request, urllib.parse, urllib.error, os

MasterGenericForm = metadataform_factory('MasterGeneric', [
    const.GNM_MASTERS_GENERIC_REMOVE,
    const.GNM_MASTERS_GENERIC_PREVENTMOBILEUPLOAD,
    const.GNM_MASTERS_GENERIC_CONTAINSADULTCONTENT,
    const.GNM_MASTERS_GENERIC_PUBLISH,
    const.GNM_MASTERS_GENERIC_STATUS,
    const.GNM_MASTERS_GENERIC_SOURCE,
    const.GNM_MASTERS_GENERIC_INTENDEDUPLOADPLATFORMS,
    const.GNM_MASTERS_GENERIC_UKONLY,
    const.GNM_MASTERS_GENERIC_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_GENERIC_UPLOADTYPE,
    const.GNM_MASTERS_GENERIC_WHOLLYOWNED,
    const.GNM_MASTERS_GENERIC_TITLEID,
    const.GNM_STORAGE_RULE_DEEP_ARCHIVE,
    const.GNM_STORAGE_RULE_DELETABLE,
    const.GNM_STORAGE_RULE_SENSITIVE,
    const.GNM_MASTERS_GENERIC_LANGUAGE,
    const.GNM_MASTERS_GENERIC_LICENSOR,
    const.GNM_MASTERS_GENERIC_PRODUCTION_OFFICE,
    const.GNM_MASTERS_GENERIC_PACFORM_LASTUPDATE
])

MasterDailyMotionForm = metadataform_factory('MasterDailyMotion', [
    const.GNM_MASTERS_DAILYMOTION_NOMOBILEACCESS,
    const.GNM_MASTERS_DAILYMOTION_DESCRIPTION,
    const.GNM_MASTERS_DAILYMOTION_CONTAINSADULTCONTENT,
    const.GNM_MASTERS_DAILYMOTION_KEYWORDS,
    const.GNM_MASTERS_DAILYMOTION_TITLE,
    const.GNM_MASTERS_DAILYMOTION_UPLOADSTATUS,
    const.GNM_MASTERS_DAILYMOTION_UPLOADLOG,
    const.GNM_MASTERS_DAILYMOTION_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_DAILYMOTION_DAILYMOTIONURL,
    const.GNM_MASTERS_DAILYMOTION_DAILYMOTIONCATEGORY,
    const.GNM_MASTERS_DAILYMOTION_OWNER,
    const.GNM_MASTERS_DAILYMOTION_HOLDINGIMAGE,
    const.GNM_MASTERS_DAILYMOTION_UPLOADTYPE,
    const.GNM_MASTERS_DAILYMOTION_STATUS,
])

MasterInteractiveForm = metadataform_factory('MasterGnmInteractive', [
    const.GNM_MASTERS_INTERACTIVE_TITLE,
    const.GNM_MASTERS_INTERACTIVE_PROJECTREF,
    const.GNM_MASTERS_INTERACTIVE_UPLOADSTATUS,
    const.GNM_MASTERS_INTERACTIVE_UPLOADLOG,
    const.GNM_MASTERS_INTERACTIVE_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_INTERACTIVE_OWNER,
    const.GNM_MASTERS_INTERACTIVE_PUBLISH,
    const.GNM_MASTERS_INTERACTIVE_REMOVE,
    const.GNM_MASTERS_INTERACTIVE_STATUS,
])

MasterWebsiteForm = metadataform_factory('MasterGnmWebsite', [
    const.GNM_MASTERS_WEBSITE_STANDFIRST,
    const.GNM_MASTERS_WEBSITE_BYLINE,
    const.GNM_MASTERS_WEBSITE_PRIMARY_TONE,
    const.GNM_MASTERS_WEBSITE_TAGS,
    const.GNM_MASTERS_WEBSITE_HEADLINE,
    const.GNM_MASTERS_WEBSITE_TRAIL,
    const.GNM_MASTERS_WEBSITE_UPLOADSTATUS,
    const.GNM_MASTERS_WEBSITE_UPLOADLOG,
])

MasterMainstreamSyndicationForm = metadataform_factory('MasterMainstreamSyndication', [
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_TITLE,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_KEYWORDS,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_DESCRIPTION,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_PUBLISH,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_REMOVE,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_CONTAINSADULTCONTENT,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_UPLOADSTATUS,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_UPLOADLOG,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_HOLDINGIMAGE,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_STATUS,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_OWNER,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_AOL_CATEGORY,
    const.GNM_MASTERS_MAINSTREAMSYNDICATION_AOL_SUBCATEGORY,
])

MasterYoutubeForm = metadataform_factory('MasterYoutube', [
    const.GNM_MASTERS_YOUTUBE_KEYWORDS,
    const.GNM_MASTERS_YOUTUBE_ALLOWRESPONSES,
    const.GNM_MASTERS_YOUTUBE_PUBLISH,
    const.GNM_MASTERS_YOUTUBE_CONTAINSADULTCONTENT,
    const.GNM_MASTERS_YOUTUBE_UPLOADSTATUS,
    const.GNM_MASTERS_YOUTUBE_ALLOWEMBEDDING,
    const.GNM_MASTERS_YOUTUBE_ALLOWRATINGS,
    const.GNM_MASTERS_YOUTUBE_DESCRIPTION,
    const.GNM_MASTERS_YOUTUBE_TITLE,
    const.GNM_MASTERS_YOUTUBE_UPLOADLOG,
    const.GNM_MASTERS_YOUTUBE_MATCHINGPOLICY,
    const.GNM_MASTERS_YOUTUBE_ALLOWCOMMENTS,
    const.GNM_MASTERS_YOUTUBE_CATEGORY,
    const.GNM_MASTERS_YOUTUBE_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_YOUTUBE_CHANNEL,
    const.GNM_MASTERS_YOUTUBE_YOUTUBEURL,
    const.GNM_MASTERS_YOUTUBE_OWNER,
    const.GNM_MASTERS_YOUTUBE_HOLDINGIMAGE,
    const.GNM_MASTERS_YOUTUBE_UPLOADTYPE,
    const.GNM_MASTERS_YOUTUBE_STATUS,
    const.GNM_MASTERS_YOUTUBE_APPLY_IMAGE_STABILISATION,
    const.GNM_MASTERS_YOUTUBE_HIDE_PUBLIC_STATISTICS,
    const.GNM_MASTERS_YOUTUBE_EMBEDDABLE,
    const.GNM_MASTERS_YOUTUBE_PICTURE_ENHANCE,
    const.GNM_MASTERS_YOUTUBE_NOTIFY_CHANNEL_SUBSCRIBERS,
    const.GNM_MASTERS_YOUTUBE_LICENSE,
])

MasterMediaAtomForm = metadataform_factory('MasterMediaAtom', [
    const.GNM_MASTERS_MEDIAATOM_ATOMID,
    const.GNM_MASTERS_MEDIAATOM_STATUS,
    const.GNM_MASTERS_MEDIAATOM_UPLOADLOG,
    const.GNM_MASTERS_MEDIAATOM_UPLOADSTATUS
])

MasterSpotifyForm = metadataform_factory('MasterSpotify', [
    const.GNM_MASTERS_SPOTIFY_LICENSOR,
    const.GNM_MASTERS_SPOTIFY_ID,
    const.GNM_MASTERS_SPOTIFY_TITLE_ID,
    const.GNM_MASTERS_SPOTIFY_UPLOAD_VERSION,
    const.GNM_MASTERS_SPOTIFY_UPLOAD_VERSION,
    const.GNM_MASTERS_SPOTIFY_TITLE,
    const.GNM_MASTERS_SPOTIFY_DESCRIPTION,
    const.GNM_MASTERS_SPOTIFY_KEYWORDS,
    const.GNM_MASTERS_SPOTIFY_PUBLISH,
    const.GNM_MASTERS_SPOTIFY_UPLOADSTATUS,
    const.GNM_MASTERS_SPOTIFY_STATUS,
    const.GNM_MASTERS_SPOTIFY_UPLOADLOG,
])

MasterFacebookForm = metadataform_factory('MasterFacebook', [
    const.GNM_MASTERS_FACEBOOK_ID,
    const.GNM_MASTERS_FACEBOOK_BACKDATE_ACCURACY,
    const.GNM_MASTERS_FACEBOOK_SCHEDULE_PUBLISH_TIME,
    const.GNM_MASTERS_FACEBOOK_CALL_TO_ACTION,
    const.GNM_MASTERS_FACEBOOK_BACKDATE_POST,
    const.GNM_MASTERS_FACEBOOK_TARGET,
    const.GNM_MASTERS_FACEBOOK_HIDE_STORY,
    const.GNM_MASTERS_FACEBOOK_TITLE,
    const.GNM_MASTERS_FACEBOOK_HOLDINGIMAGE,
    const.GNM_MASTERS_FACEBOOK_HOLDINGIMAGE_16X9,
    const.GNM_MASTERS_FACEBOOK_BACKDATED_TIME,
    const.GNM_MASTERS_FACEBOOK_DESCRIPTION,
    const.GNM_MASTERS_FACEBOOK_HIDE_BACKDATED_POST,
    const.GNM_MASTERS_FACEBOOK_STATUS,
    const.GNM_MASTERS_FACEBOOK_UPLOAD_AS,
    const.GNM_MASTERS_FACEBOOK_UPLOADSTATUS,
    const.GNM_MASTERS_FACEBOOK_UPLOADLOG,
])

MasterFacebookCallToActionForm = metadataform_factory('CallToAction', [
    const.GNM_MASTERS_FACEBOOK_ACTION_TYPE,
    const.GNM_MASTERS_FACEBOOK_ACTION_LINK,
    const.GNM_MASTERS_FACEBOOK_ACTION_APP_LINK,
    const.GNM_MASTERS_FACEBOOK_ACTION_PAGE_ID,
    const.GNM_MASTERS_FACEBOOK_ACTION_OFFER_ID,
    const.GNM_MASTERS_FACEBOOK_ACTION_APPLICATION,
    const.GNM_MASTERS_FACEBOOK_ACTION_LINK_TITLE,
    const.GNM_MASTERS_FACEBOOK_ACTION_DESCRIPTION,
    const.GNM_MASTERS_FACEBOOK_ACTION_LINK_CAPTION,
    const.GNM_MASTERS_FACEBOOK_ACTION_PRODUCT_LINK,
    const.GNM_MASTERS_FACEBOOK_ACTION_GET_MOVIE_SHOWTIMES,
    const.GNM_MASTERS_FACEBOOK_ACTION_SPONSORED,
    const.GNM_MASTERS_FACEBOOK_ACTION_SPONSOR_LINK,
    const.GNM_MASTERS_FACEBOOK_ACTION_SPONSOR_IMAGE_URL,
])

MasterMediawallForm = metadataform_factory('MasterMediawall', [
    const.GNM_MASTERMEDIAWALL_OUTPUT_FILENAME,
    const.GNM_MASTERMEDIAWALL_MEDIA_WALL_FLAGS,
    const.GNM_MASTERMEDIAWALL_PUBLICATION_TIME,
    const.GNM_MASTERMEDIAWALL_UPLOADLOG,
    const.GNM_MASTERMEDIAWALL_STATUS,
    const.GNM_MASTERMEDIAWALL_UPLOADSTATUS,
])

class DjangoS3UploadForm(Form):
    from s3direct.widgets import S3DirectWidget
    video_file_url = URLField(widget=S3DirectWidget(dest='pluto_failsafe'))


class MastersSearchForm(Form):
    freetext = CharField(required=False, widget=TextInput(attrs={'placeholder': 'Search all masters'}))
