

DELIVERABLE_ASSET_TYPE_VIDEO_FULL_MASTER = 1
DELIVERABLE_ASSET_TYPE_VIDEO_INTERNATIONAL_MASTER = 2

DELIVERABLE_ASSET_TYPE_AUDIO_NATURAL_SOUND = 3
DELIVERABLE_ASSET_TYPE_AUDIO_MUSIC = 4
DELIVERABLE_ASSET_TYPE_AUDIO_VOICEOVER = 5
DELIVERABLE_ASSET_TYPE_AUDIO_FX = 6
DELIVERABLE_ASSET_TYPE_AUDIO_SYNC_SOUND = 12

DELIVERABLE_ASSET_TYPE_OTHER_SUBTITLE = 7
DELIVERABLE_ASSET_TYPE_OTHER_POST_PRODUCTION_SCRIPT = 8
DELIVERABLE_ASSET_TYPE_OTHER_TRAILER = 9
DELIVERABLE_ASSET_TYPE_OTHER_PROMO_STILLS = 10
DELIVERABLE_ASSET_TYPE_OTHER_PAC_FORMS = 11
DELIVERABLE_ASSET_TYPE_OTHER_MISCELLANEOUS = 13


DELIVERABLE_ASSET_TYPES_VIDEO = (
    (DELIVERABLE_ASSET_TYPE_VIDEO_FULL_MASTER, 'Full master'),
    (DELIVERABLE_ASSET_TYPE_VIDEO_INTERNATIONAL_MASTER, 'Clean Master (Textless, no branding)'),
)

DELIVERABLE_ASSET_TYPES_AUDIO = (
    (DELIVERABLE_ASSET_TYPE_AUDIO_NATURAL_SOUND, 'Natural sound'),
    (DELIVERABLE_ASSET_TYPE_AUDIO_MUSIC, 'Music'),
    (DELIVERABLE_ASSET_TYPE_AUDIO_VOICEOVER, 'Voiceover'),
    (DELIVERABLE_ASSET_TYPE_AUDIO_FX, 'FX'),
    (DELIVERABLE_ASSET_TYPE_AUDIO_SYNC_SOUND, 'Sync sound'),
)

DELIVERABLE_ASSET_TYPES_OTHER = (
    (DELIVERABLE_ASSET_TYPE_OTHER_SUBTITLE, 'Subtitles'),
    (DELIVERABLE_ASSET_TYPE_OTHER_POST_PRODUCTION_SCRIPT, 'Post-production script'),
    (DELIVERABLE_ASSET_TYPE_OTHER_TRAILER, 'Trailer'),
    (DELIVERABLE_ASSET_TYPE_OTHER_PROMO_STILLS, 'Promo stills'),
    (DELIVERABLE_ASSET_TYPE_OTHER_PAC_FORMS, 'PAC forms'),
    (DELIVERABLE_ASSET_TYPE_OTHER_MISCELLANEOUS, 'Miscellaneous'),
)

DELIVERABLE_ASSET_TYPES = DELIVERABLE_ASSET_TYPES_VIDEO + DELIVERABLE_ASSET_TYPES_AUDIO + DELIVERABLE_ASSET_TYPES_OTHER

DELIVERABLE_ASSET_TYPES_DICT = dict(DELIVERABLE_ASSET_TYPES)

DELIVERABLE_ASSET_TYPE_CHOICES = (
    ('Master', DELIVERABLE_ASSET_TYPES_VIDEO),
    ('Sound', DELIVERABLE_ASSET_TYPES_AUDIO),
    ('Other', DELIVERABLE_ASSET_TYPES_OTHER)
)


DELIVERABLE_STATUS_FILES_TO_INGEST = 0
DELIVERABLE_STATUS_ALL_FILES_INGESTED = 1
DELIVERABLE_STATUSES = (
    (DELIVERABLE_STATUS_FILES_TO_INGEST, 'Files to ingest'),
    (DELIVERABLE_STATUS_ALL_FILES_INGESTED, 'All files ingested')
)
DELIVERABLE_STATUSES_DICT = dict(DELIVERABLE_STATUSES)

# Deliverable asset status
DELIVERABLE_ASSET_STATUS_NOT_INGESTED = 0
DELIVERABLE_ASSET_STATUS_INGESTING = 1
DELIVERABLE_ASSET_STATUS_INGESTED = 2
DELIVERABLE_ASSET_STATUS_TRANSCODING = 4
DELIVERABLE_ASSET_STATUS_TRANSCODED = 5
DELIVERABLE_ASSET_STATUS_TRANSCODE_FAILED = 6
DELIVERABLE_ASSET_STATUS_INGEST_FAILED = 3
DELIVERABLE_ASSET_STATUSES = (
    (DELIVERABLE_ASSET_STATUS_NOT_INGESTED, 'Not ingested'),
    (DELIVERABLE_ASSET_STATUS_INGESTING, 'Ingesting'),
    (DELIVERABLE_ASSET_STATUS_INGESTED, 'Ingested'),
    (DELIVERABLE_ASSET_STATUS_INGEST_FAILED, 'Ingest failed'),
    (DELIVERABLE_ASSET_STATUS_TRANSCODING, "Transcoding"),
    (DELIVERABLE_ASSET_STATUS_TRANSCODE_FAILED, "Transcode Failed"),
    (DELIVERABLE_ASSET_STATUS_TRANSCODED, "Ready")
)

DELIVERABLE_ASSET_STATUSES_DICT = dict(DELIVERABLE_ASSET_STATUSES)

UPLOAD_STATUS = [
    ('Not ready', 'Not ready'),
    ('Ready for Upload', 'Ready for Upload'),
    ('Uploading', 'Uploading'),
    ('Upload Failed', 'Upload Failed'),
    ('Upload Complete', 'Upload Complete')
]

PRODUCTION_OFFICE = [
    ('UK', 'UK'),
    ('US', 'US'),
    ('AUS', 'AUS')
]

PRIMARY_TONE = [
    ('News', 'News'),
    ('Explainer', 'Explainer'),
    ('Documentary', 'Documentary'),
    ('Comment', 'Comment'),
    ('Analysis', 'Analysis'),
    ('Feature', 'Feature'),
    ('Interview', 'Interview'),
    ('Performance', 'Performance')
]

PUBLICATION_STATUS = [
    ('Unpublished', 'Unpublished'),
    ('Published', 'Published'),
    ('Superceded', 'Superceded')
]