# Asset metadata fields
GNM_ASSET_TITLE = 'title'
GNM_ASSET_KEYWORDS = 'gnm_asset_keywords'
GNM_ASSET_FILENAME = 'gnm_asset_filename'
GNM_ASSET_STATUS = 'gnm_asset_status'
GNM_ASSET_CREATEDBY = 'gnm_asset_createdby'
GNM_ASSET_DESCRIPTION = 'gnm_asset_description'
GNM_ASSET_CATEGORY = 'gnm_asset_category'
GNM_ASSET_OWNER = 'gnm_asset_owner'
GNM_ASSET_FILE_CREATED = 'gnm_asset_file_created'
GNM_ASSET_FILMING_LOCATION = 'gnm_asset_filming_location'
GNM_ASSET_FILE_LAST_MODIFIED = 'gnm_asset_file_last_modified'
GNM_ASSET_RESTRICTIONS_NOTES = 'gnm_asset_restrictions_notes'
GNM_ASSET_FEE_NOTES = 'gnm_asset_fee_notes'
GNM_ASSET_RESTRICTIONS_APPLY = 'gnm_asset_restrictions_apply'
GNM_CROPPED_FROM = 'gnm_cropped_from'

GNM_ASSET_STATUS_READY_FOR_ARCHIVE = 'Ready for Archive or Deletion'
GNM_ASSET_STATUS_ARCHIVED_TO_EXTERNAL = 'Archived to External'

GNM_ASSET_CATEGORY_GUARDIAN_MASTER = 'Master'
GNM_ASSET_CATEGORY_GUARDIAN_RUSHES = 'Rushes'
GNM_ASSET_CATEGORY_REUTERS_PACKAGE = 'Reuters'

GNM_MM_REF = 'gnm_mm_ref'
GNM_MM_COPYRIGHT = 'gnm_mm_copyright'
GNM_MM_PHOTOGRAPHER = 'gnm_mm_photographer'
GNM_MM_PROVIDER = 'gnm_mm_provider'
GNM_MM_HEADLINE = 'gnm_mm_headline'
GNM_MM_CAPTION = 'gnm_mm_caption'

# Master metadata fields
GNM_MASTERS_DAILYMOTION_NOMOBILEACCESS = 'gnm_master_dailymotion_nomobileaccess'
GNM_MASTERS_DAILYMOTION_DESCRIPTION = 'gnm_master_dailymotion_description'
GNM_MASTERS_DAILYMOTION_PUBLISH = 'gnm_master_dailymotion_publish'
GNM_MASTERS_DAILYMOTION_REMOVE = 'gnm_master_dailymotion_remove'
GNM_MASTERS_DAILYMOTION_CONTAINSADULTCONTENT = 'gnm_master_dailymotion_containsadultcontent'
GNM_MASTERS_DAILYMOTION_KEYWORDS = 'gnm_master_dailymotion_keywords'
GNM_MASTERS_DAILYMOTION_HOLDINGIMAGE_16X9 = 'gnm_master_dailymotion_holdingimage_16x9'
GNM_MASTERS_DAILYMOTION_AUTHOR = 'gnm_master_dailymotion_author'
GNM_MASTERS_DAILYMOTION_CATEGORY = 'gnm_master_dailymotion_category'
GNM_MASTERS_DAILYMOTION_TITLE = 'gnm_master_dailymotion_title'
GNM_MASTERS_DAILYMOTION_UPLOADSTATUS = 'gnm_master_dailymotion_uploadstatus'
GNM_MASTERS_DAILYMOTION_UPLOADLOG = 'gnm_master_dailymotion_uploadlog'
GNM_MASTERS_DAILYMOTION_DAILYMOTIONURL = 'gnm_master_dailymotion_dailymotionurl'
GNM_MASTERS_DAILYMOTION_DAILYMOTIONCHANNEL = 'gnm_master_dailymotion_dailymotionchannel'
GNM_MASTERS_DAILYMOTION_DAILYMOTIONCATEGORY = 'gnm_master_dailymotion_dailymotioncategory'
GNM_MASTERS_DAILYMOTION_OWNER = 'gnm_master_dailymotion_owner'
GNM_MASTERS_DAILYMOTION_HOLDINGIMAGE = 'gnm_master_dailymotion_holdingimage'
GNM_MASTERS_DAILYMOTION_UPLOADTYPE = 'gnm_master_dailymotion_uploadtype'
GNM_MASTERS_DAILYMOTION_STATUS = 'gnm_master_dailymotion_status'
GNM_MASTERS_GENERIC_REMOVE = 'gnm_master_generic_remove'
GNM_MASTERS_GENERIC_PREVENTMOBILEUPLOAD = 'gnm_master_generic_preventmobileupload'
GNM_MASTERS_GENERIC_CONTAINSADULTCONTENT = 'gnm_master_generic_containsadultcontent'
GNM_MASTERS_GENERIC_OWNER = 'gnm_master_generic_owner'
GNM_MASTERS_GENERIC_PUBLISH = 'gnm_master_generic_publish'
GNM_MASTERS_GENERIC_TITLEID = 'gnm_master_generic_titleid'
GNM_MASTERS_GENERIC_INTENDEDUPLOADPLATFORMS = 'gnm_master_generic_intendeduploadplatforms'
GNM_MASTERS_GENERIC_UKONLY = 'gnm_master_generic_ukonly'
GNM_MASTERS_GENERIC_HOLDINGIMAGE_16X9 = 'gnm_master_generic_holdingimage_16x9'
GNM_MASTERS_GENERIC_HOLDINGIMAGE_5X3 = 'gnm_master_generic_holdingimage_5x3'
GNM_MASTERS_GENERIC_UPLOADTYPE = 'gnm_master_generic_uploadtype'
GNM_MASTERS_GENERIC_WHOLLYOWNED = 'gnm_master_generic_whollyowned'
GNM_MASTERS_GENERIC_STATUS = 'gnm_master_generic_status'
GNM_MASTERS_GENERIC_SOURCE = 'gnm_master_generic_source'
GNM_MASTERS_GENERIC_PACDATA_STAUS = 'gnm_master_pacdata_status'
GNM_MASTERS_GENERIC_CONSISTS_OF_ASSETS = "gnm_master_generic_consists_of_assets"
GNM_MASTERS_GENERIC_LANGUAGE = 'gnm_master_language'
GNM_MASTERS_GENERIC_LICENSOR = 'gnm_master_licensor'
GNM_MASTERS_GENERIC_PRODUCTION_OFFICE = 'gnm_master_generic_production_office'
GNM_MASTERS_GENERIC_PACFORM_LASTUPDATE = 'gnm_master_generic_pacform_lastupdate'
GNM_MASTERS_GENERIC_PACFORM_LASTERROR = 'gnm_master_generic_pacform_lasterror'
GNM_MASTERS_INTERACTIVE_TITLE = 'gnm_master_interactive_title'
GNM_MASTERS_INTERACTIVE_OWNER = 'gnm_master_interactive_owner'
GNM_MASTERS_INTERACTIVE_PROJECTREF = 'gnm_master_interactive_projectref'
GNM_MASTERS_INTERACTIVE_UPLOADSTATUS = 'gnm_master_interactive_uploadstatus'
GNM_MASTERS_INTERACTIVE_UPLOADLOG = 'gnm_master_interactive_uploadlog'
GNM_MASTERS_INTERACTIVE_HOLDINGIMAGE_16X9 = 'gnm_master_interactive_holdingimage_16x9'
GNM_MASTERS_INTERACTIVE_PUBLISH = 'gnm_master_interactive_publish'
GNM_MASTERS_INTERACTIVE_REMOVE = 'gnm_master_interactive_remove'
GNM_MASTERS_INTERACTIVE_STATUS = 'gnm_master_interactive_status'
GNM_MASTERS_WEBSITE_EDIT_URL = 'gnm_master_website_edit_url'
GNM_MASTERS_WEBSITE_STANDFIRST = 'gnm_master_website_standfirst'
GNM_MASTERS_WEBSITE_BYLINE = 'gnm_master_website_byline'
GNM_MASTERS_WEBSITE_TAGS = 'gnm_master_website_tags'
GNM_MASTERS_WEBSITE_PRIMARY_TONE = 'gnm_master_website_primary_tone'
GNM_MASTERS_WEBSITE_HEADLINE = 'gnm_master_website_headline'
GNM_MASTERS_WEBSITE_LINKTEXT = 'gnm_master_website_linktext'
GNM_MASTERS_WEBSITE_TRAIL = 'gnm_master_website_trail'
GNM_MASTERS_WEBSITE_UPLOADSTATUS = 'gnm_master_website_uploadstatus'
GNM_MASTERS_WEBSITE_UPLOADLOG = 'gnm_master_website_uploadlog'
GNM_MASTERS_MAINSTREAMSYNDICATION_TITLE = 'gnm_master_mainstreamsyndication_title'
GNM_MASTERS_MAINSTREAMSYNDICATION_CATEGORY = 'gnm_master_mainstreamsyndication_category'
GNM_MASTERS_MAINSTREAMSYNDICATION_KEYWORDS = 'gnm_master_mainstreamsyndication_keywords'
GNM_MASTERS_MAINSTREAMSYNDICATION_DESCRIPTION = 'gnm_master_mainstreamsyndication_description'
GNM_MASTERS_MAINSTREAMSYNDICATION_PUBLISH = 'gnm_master_mainstreamsyndication_publish'
GNM_MASTERS_MAINSTREAMSYNDICATION_REMOVE = 'gnm_master_mainstreamsyndication_remove'
GNM_MASTERS_MAINSTREAMSYNDICATION_HOLDINGIMAGE_16X9 = 'gnm_master_mainstreamsyndication_holdingimage_16x9'
GNM_MASTERS_MAINSTREAMSYNDICATION_CONTAINSADULTCONTENT = 'gnm_master_mainstreamsyndication_containsadultcontent'
GNM_MASTERS_MAINSTREAMSYNDICATION_AUTHOR = 'gnm_master_mainstreamsyndication_author'
GNM_MASTERS_MAINSTREAMSYNDICATION_UPLOADSTATUS = 'gnm_master_mainstreamsyndication_uploadstatus'
GNM_MASTERS_MAINSTREAMSYNDICATION_UPLOADLOG = 'gnm_master_mainstreamsyndication_uploadlog'
GNM_MASTERS_MAINSTREAMSYNDICATION_HOLDINGIMAGE = 'gnm_master_mainstreamsyndication_holdingimage'
GNM_MASTERS_MAINSTREAMSYNDICATION_STATUS = 'gnm_master_mainstreamsyndication_status'
GNM_MASTERS_MAINSTREAMSYNDICATION_OWNER = 'gnm_master_mainstreamsyndication_owner'
GNM_MASTERS_MAINSTREAMSYNDICATION_AOL_CATEGORY = 'gnm_master_mainstreamsyndication_aol_master_category'
GNM_MASTERS_MAINSTREAMSYNDICATION_AOL_SUBCATEGORY = 'gnm_master_mainstreamsyndication_aol_subcategory'
GNM_MASTERS_YOUTUBE_KEYWORDS = 'gnm_master_youtube_keywords'
GNM_MASTERS_YOUTUBE_ALLOWRESPONSES = 'gnm_master_youtube_allowresponses'
GNM_MASTERS_YOUTUBE_PUBLISH = 'gnm_master_youtube_publish'
GNM_MASTERS_YOUTUBE_REMOVE = 'gnm_master_youtube_remove'
GNM_MASTERS_YOUTUBE_HOLDINGIMAGE_16X9 = 'gnm_master_youtube_holdingimage_16x9'
GNM_MASTERS_YOUTUBE_CONTAINSADULTCONTENT = 'gnm_master_youtube_containsadultcontent'
GNM_MASTERS_YOUTUBE_UPLOADSTATUS = 'gnm_master_youtube_uploadstatus'
GNM_MASTERS_YOUTUBE_ALLOWEMBEDDING = 'gnm_master_youtube_allowembedding'
GNM_MASTERS_YOUTUBE_ALLOWRATINGS = 'gnm_master_youtube_allowratings'
GNM_MASTERS_YOUTUBE_DESCRIPTION = 'gnm_master_youtube_description'
GNM_MASTERS_YOUTUBE_TITLE = 'gnm_master_youtube_title'
GNM_MASTERS_YOUTUBE_UPLOADLOG = 'gnm_master_youtube_uploadlog'
GNM_MASTERS_YOUTUBE_MATCHINGPOLICY = 'gnm_master_youtube_matchingpolicy'
GNM_MASTERS_YOUTUBE_ALLOWCOMMENTS = 'gnm_master_youtube_allowcomments'
GNM_MASTERS_YOUTUBE_CATEGORY = 'gnm_master_youtube_category'
GNM_MASTERS_YOUTUBE_LICENSE = 'gnm_master_youtube_license'
GNM_MASTERS_YOUTUBE_CHANNEL = 'gnm_master_youtube_channelid'
GNM_MASTERS_YOUTUBE_YOUTUBEURL = 'gnm_master_youtube_youtubeurl'
GNM_MASTERS_YOUTUBE_OWNER = 'gnm_master_youtube_owner'
GNM_MASTERS_YOUTUBE_HOLDINGIMAGE = 'gnm_master_youtube_holdingimage'
GNM_MASTERS_YOUTUBE_UPLOADTYPE = 'gnm_master_youtube_uploadtype'
GNM_MASTERS_YOUTUBE_STATUS = 'gnm_master_youtube_status'
GNM_MASTERS_YOUTUBE_APPLY_IMAGE_STABILISATION = 'gnm_master_youtube_apply_image_stabilisation'
GNM_MASTERS_YOUTUBE_HIDE_PUBLIC_STATISTICS = 'gnm_master_youtube_hide_public_statistics'
GNM_MASTERS_YOUTUBE_EMBEDDABLE = 'gnm_master_youtube_embeddable'
GNM_MASTERS_YOUTUBE_PICTURE_ENHANCE = 'gnm_master_youtube_picture_enhance'
GNM_MASTERS_YOUTUBE_NOTIFY_CHANNEL_SUBSCRIBERS = 'gnm_master_youtube_notify_channel_subscribers'

GNM_MASTERS_GENERIC_STATUS_PUBLISHED = 'Published'

# media atom fields
GNM_MASTERS_MEDIAATOM_ATOMID = 'gnm_master_mediaatom_atomid'
GNM_MASTERS_MEDIAATOM_STATUS = 'gnm_master_mediaatom_status'
GNM_MASTERS_MEDIAATOM_UPLOADLOG = 'gnm_master_mediaatom_uploadlog'
GNM_MASTERS_MEDIAATOM_UPLOADSTATUS = 'gnm_master_mediaatom_uploadstatus'
GNM_MASTERS_MEDIAATOM_UPLOADEDBY = 'gnm_master_mediaatom_uploaded_by'

GNM_MASTERS_SPOTIFY_LICENSOR = 'gnm_master_spotify_licensor'
GNM_MASTERS_SPOTIFY_TITLE_ID = 'gnm_master_spotify_title_id'
GNM_MASTERS_SPOTIFY_ID = 'gnm_master_spotify_id'
GNM_MASTERS_SPOTIFY_UPLOAD_VERSION = 'gnm_master_spotify_upload_version'
GNM_MASTERS_SPOTIFY_TITLE = 'gnm_master_spotify_title'
GNM_MASTERS_SPOTIFY_DESCRIPTION = 'gnm_master_spotify_description'
GNM_MASTERS_SPOTIFY_KEYWORDS = 'gnm_master_spotify_keywords'
GNM_MASTERS_SPOTIFY_PUBLISH = 'gnm_master_spotify_publish'
GNM_MASTERS_SPOTIFY_UPLOADSTATUS = 'gnm_master_spotify_uploadstatus'
GNM_MASTERS_SPOTIFY_STATUS = 'gnm_master_spotify_status'
GNM_MASTERS_SPOTIFY_UPLOADLOG = 'gnm_master_spotify_uploadlog'
GNM_MASTERS_FACEBOOK_ID = 'gnm_master_facebook_id'
GNM_MASTERS_FACEBOOK_BACKDATE_ACCURACY = 'gnm_master_facebook_backdate_accuracy'
GNM_MASTERS_FACEBOOK_UNLISTED = 'gnm_master_facebook_unlisted'
GNM_MASTERS_FACEBOOK_UNLISTED_TRUE = 'master_facebook_unlisted'
GNM_MASTERS_FACEBOOK_CALL_TO_ACTION = 'gnm_master_facebook_call_to_action'
GNM_MASTERS_FACEBOOK_CALL_TO_ACTION_TRUE = 'master_facebook_call_to_action'
GNM_MASTERS_FACEBOOK_BACKDATE_POST = 'gnm_master_facebook_backdate_post'
GNM_MASTERS_FACEBOOK_BACKDATE_POST_TRUE = 'master_facebook_backdate_post'
GNM_MASTERS_FACEBOOK_PUBLISH_VIDEO = 'gnm_master_facebook_publish_video'
GNM_MASTERS_FACEBOOK_PUBLISH_VIDEO_TRUE = 'master_facebook_publish_video'
GNM_MASTERS_FACEBOOK_TARGET = 'gnm_master_facebook_target'
GNM_MASTERS_FACEBOOK_SCHEDULE_PUBLISH_TIME = 'gnm_master_facebook_schedule_publish_time'
GNM_MASTERS_FACEBOOK_HIDE_STORY = 'gnm_master_facebook_hide_story'
GNM_MASTERS_FACEBOOK_HIDE_STORY_TRUE = 'master_facebook_hide_story'
GNM_MASTERS_FACEBOOK_UPLOADSTATUS = 'gnm_master_facebook_uploadstatus'
GNM_MASTERS_FACEBOOK_STATUS = 'gnm_master_facebook_status'
GNM_MASTERS_FACEBOOK_UPLOAD_AS = 'gnm_master_facebook_upload_as'
GNM_MASTERS_FACEBOOK_UPLOADLOG = 'gnm_master_facebook_uploadlog'
GNM_MASTERS_FACEBOOK_TITLE = 'gnm_master_facebook_title'
GNM_MASTERS_FACEBOOK_HOLDINGIMAGE = 'gnm_master_facebook_holdingimage'
GNM_MASTERS_FACEBOOK_HOLDINGIMAGE_16X9 = 'gnm_master_facebook_holdingimage_16x9'
GNM_MASTERS_FACEBOOK_BACKDATED_TIME = 'gnm_master_facebook_backdated_time'
GNM_MASTERS_FACEBOOK_DESCRIPTION = 'gnm_master_facebook_description'
GNM_MASTERS_FACEBOOK_HIDE_BACKDATED_POST = 'gnm_master_facebook_hide_backdated_post'
GNM_MASTERS_FACEBOOK_HIDE_BACKDATED_POST_TRUE = 'master_facebook_hide_backdated_post'
GNM_MASTERS_FACEBOOK_ACTION_TYPE = "gnm_call_to_action_type"
GNM_MASTERS_FACEBOOK_ACTION_LINK = "gnm_call_to_action_link"
GNM_MASTERS_FACEBOOK_ACTION_APP_LINK = "gnm_call_to_action_app_link"
GNM_MASTERS_FACEBOOK_ACTION_PAGE_ID = "gnm_call_to_action_page_id"
GNM_MASTERS_FACEBOOK_ACTION_OFFER_ID = "gnm_call_to_action_offer_id"
GNM_MASTERS_FACEBOOK_ACTION_APPLICATION = "gnm_call_to_action_application"
GNM_MASTERS_FACEBOOK_ACTION_LINK_TITLE = "gnm_call_to_action_link_title"
GNM_MASTERS_FACEBOOK_ACTION_DESCRIPTION = "gnm_call_to_action_link_description"
GNM_MASTERS_FACEBOOK_ACTION_LINK_CAPTION = "gnm_call_to_action_link_caption"
GNM_MASTERS_FACEBOOK_ACTION_PRODUCT_LINK = "gnm_call_to_action_product_link"
GNM_MASTERS_FACEBOOK_ACTION_GET_MOVIE_SHOWTIMES = "gnm_call_to_action_get_movie_showtimes"
GNM_MASTERS_FACEBOOK_ACTION_SPONSORED = "gnm_call_to_action_sponsored"
GNM_MASTERS_FACEBOOK_ACTION_SPONSOR_LINK = "gnm_call_to_action_sponsor_link"
GNM_MASTERS_FACEBOOK_ACTION_SPONSOR_IMAGE_URL = "gnm_call_to_action_sponsor_image_url"

#MasterMediawall metadata contstants

GNM_MASTERMEDIAWALL_OUTPUT_FILENAME = 'gnm_mastermediawall_output_filename'
GNM_MASTERMEDIAWALL_MEDIA_WALL_FLAGS = 'gnm_mastermediawall_media_wall_flags'
GNM_MASTERMEDIAWALL_UPLOADLOG = 'gnm_mastermediawall_uploadlog'
GNM_MASTERMEDIAWALL_STATUS = 'gnm_mastermediawall_status'
GNM_MASTERMEDIAWALL_UPLOADSTATUS = 'gnm_mastermediawall_uploadstatus'
GNM_MASTERMEDIAWALL_PUBLICATION_TIME = 'gnm_mastermediawall_publication_time'

# Field for storing type data on collections and items
GNM_TYPE = 'gnm_type'

GNM_JOB_ID = 'gnm_job_id'

GNM_USER_SKIPPED_EDL_UPLOAD = 'gnm_user_skipped_edl_upload'


# Item types
GNM_MASTER_TYPE = 'Master'
GNM_ASSET_TYPE = 'Asset'
GNM_PROJECTFILE_TYPE = 'ProjectFile'
GNM_HOLDING_IMAGE_TYPE = 'HoldingImage'
GNM_CROP_IMAGE_TYPE = 'CroppedImage'

# Field prefix - Custom Guardian fields should have this prefix in vidispine
GNM_FIELD_PREFIX = 'gnm_'


# Vidispine fields
VS_COLLECTIONID = 'collectionId'
VS_ITEMID = 'itemId'
VS_MEDIATYPE = 'mediaType'
VS_MIMETYPE = 'mimeType'
VS_SHAPETAG = 'shapeTag'
VS_USER = 'user'
VS_CREATED = 'created'
VS_ORIGINAL_FILENAME = 'originalFilename'
VS_ORIGINAL_FORMAT = 'originalFormat'
VS_ORIGINAL_HEIGHT = 'originalHeight'
VS_ORIGINAL_WIDTH = 'originalWidth'
VS_ORIGINAL_AUDIO_CODEC = 'originalAudioCodec'
VS_ORIGINAL_VIDEO_CODEC = 'originalVideoCodec'
VS_DURATION_SECONDS = 'durationSeconds'
VS_DURATION_TIMECODE = 'durationTimeCode'

VS_ANCESTOR_COLLECTION_SIZE = '__ancestor_collection_size'
VS_ANCESTOR_COLLECTION = '__ancestor_collection'
VS_COLLECTION_SIZE = '__collection_size'
VS_COLLECTION = '__collection'
VS_PARENT_COLLECTION_SIZE = '__parent_collection_size'
VS_PARENT_COLLECTION = '__parent_collection'
VS_CHILD_COLLECTION_SIZE = '__child_collection_size'
VS_CHILD_COLLECTION = '__child_collection'
VS_PLACEHOLDER_SHAPE_SIZE = '__placeholder_shape_size'
VS_SHAPE_SIZE = '__shape_size'
VS_SHAPE = '__shape'
VS_VERSION_COUNT = '__version_count'
VS_VERSION = '__version'
VS_STORAGE_ORIGINAL_SIZE = '__storage_original_size'
VS_STORAGE_SIZE = '__storage_size'
VS_STORAGEGROUP_SIZE = '__storagegroup_size'
VS_SEQUENCE_SIZE = '__sequence_size'
VS_FOLDER_MAPPED = '__folder_mapped'
VS_METADATA_LAST_MODIFIED = '__metadata_last_modified'


# Internal date format.
VS_DATEFORMAT = '%Y-%m-%d'
VS_DATETIMEFORMAT = '%Y-%m-%dT%H:%M:%S'

# Cache timeouts
CACHE_SHORT = 60
CACHE_MEDIUM = 60 * 60
CACHE_LONG = 60 * 60 * 24