# Generated by Django 3.0.9 on 2020-08-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=61)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(blank=True, choices=[('Master', ((1, 'Full master'), (2, 'Clean Master (Textless, no branding)'))), ('Sound', ((3, 'Natural sound'), (4, 'Music'), (5, 'Voiceover'), (6, 'FX'), (12, 'Sync sound'))), ('Other', ((7, 'Subtitles'), (8, 'Post-production script'), (9, 'Trailer'), (10, 'Promo stills'), (11, 'PAC forms'), (13, 'Miscellaneous')))], null=True)),
                ('filename', models.TextField(blank=True, null=True)),
                ('absolute_path', models.TextField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('access_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
                ('changed_dt', models.DateTimeField(blank=True, null=True)),
                ('job_id', models.TextField(blank=True, null=True)),
                ('item_id', models.TextField(blank=True, null=True)),
                ('ingest_complete_dt', models.DateTimeField(blank=True, null=True)),
                ('file_removed_dt', models.DateTimeField(blank=True, null=True)),
                ('created_from_existing_item', models.BooleanField(default=False)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='gnm_deliverables.Deliverable')),
            ],
        ),
    ]
