# Generated by Django 3.1 on 2020-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0002_auto_20200814_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymotion',
            name='etag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gnmwebsite',
            name='etag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainstream',
            name='etag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='etag',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
