# Generated by Django 3.1 on 2020-08-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0002_auto_20200814_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not ingested'), (1, 'Ingesting'), (2, 'Ingested'), (3, 'Ingest failed')], default=0),
        ),
    ]
