# Generated by Django 3.1 on 2020-08-27 12:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0003_auto_20200826_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymotion',
            name='daily_motion_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mainstream',
            name='mainstream_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='youtube_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='youtube_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='youtube_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
