# Generated by Django 3.1 on 2020-08-26 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0003_auto_20200825_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymotion',
            name='etag',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='gnmwebsite',
            name='etag',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mainstream',
            name='etag',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='etag',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
