# Generated by Django 3.1 on 2020-08-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0005_auto_20200827_1254'),
        ('gnm_deliverables', '0004_deliverableasset_status'),
    ]

    operations = [
    ]
