# Generated by Django 3.1 on 2020-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0006_merge_20200830_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='pluto_core_project_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverableasset',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not ingested'), (1, 'Ingesting'), (2, 'Ingested'), (3, 'Ingest failed'), (4, 'Transcoding'), (6, 'Transcode Failed'), (5, 'Ready')], default=0),
        ),
    ]
