# Generated by Django 3.1 on 2020-09-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0007_auto_20200904_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableasset',
            name='atom_id',
            field=models.UUIDField(null=True),
        ),
    ]
