# Generated by Django 3.1 on 2020-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0008_deliverableasset_atom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstream',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverableasset',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[('Master', ((1, 'Full master'), (2, 'Clean Master (Textless, no branding)'), (14, 'Migrated master'))), ('Sound', ((3, 'Natural sound'), (4, 'Music'), (5, 'Voiceover'), (6, 'FX'), (12, 'Sync sound'))), ('Other', ((7, 'Subtitles'), (8, 'Post-production script'), (9, 'Trailer'), (10, 'Promo stills'), (11, 'PAC forms'), (13, 'Miscellaneous')))], null=True),
        ),
    ]
