# Generated by Django 3.1 on 2020-10-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0009_auto_20201020_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymotion',
            name='daily_motion_category',
            field=models.TextField(default='news'),
        ),
    ]
