# Generated by Django 3.1 on 2020-10-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0010_auto_20201020_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableasset',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverableasset',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
