# Generated by Django 3.1.7 on 2021-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0011_auto_20201022_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='youtube_categories',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='youtube_channels',
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_category',
            field=models.CharField(default='invalid', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_channel',
            field=models.CharField(default='invalid', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverableasset',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[('Master', ((1, 'Full master'), (2, 'Clean Master (Textless, no branding)'), (14, 'Migrated master'))), ('Sound', ((3, 'Natural sound'), (4, 'Music'), (5, 'Voiceover'), (6, 'FX'), (12, 'Sync sound'), (15, 'Podcast Master'))), ('Other', ((7, 'Subtitles'), (8, 'Post-production script'), (9, 'Trailer'), (10, 'Promo stills'), (11, 'PAC forms'), (13, 'Miscellaneous')))], null=True),
        ),
    ]
