# Generated by Django 3.1.10 on 2021-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0012_auto_20210301_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverableasset',
            name='linked_to_lowres',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
