# Generated by Django 3.1.13 on 2021-11-23 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0013_deliverableasset_linked_to_lowres'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyndicationNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('username', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=32768)),
                ('deliverable_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnm_deliverables.deliverableasset')),
            ],
        ),
    ]
