# Generated by Django 3.1.13 on 2021-12-01 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnm_deliverables', '0015_auto_20211201_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReutersConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_on_channel', models.BooleanField(default=False)),
                ('etag', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='deliverableasset',
            name='reutersconnect_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gnm_deliverables.reutersconnect'),
        ),
    ]
